const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// id autogenerated for the book
const bookSchema = new Schema({
    name: String,
    genre: String,
    authorId: String
});
// model or collection called book based on the schema called the bookSchema
module.exports = mongoose.model('Book', bookSchema);